Manager/Controllers/CommentController.cs
using Shop.Bussiness.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Manager.Controllers
{
    public class CommentController : GenericApiController
    {
        // GET: Comment
        public ActionResult Index()
        {

            var model = GetService<CommentService>().GetComments();
            return View(model);
        }


        public ActionResult Delete(int id)
        {
            GetService<CommentService>().DeleteComment(id);
            return RedirectToAction("Index");
        }
    }
}

Manager/Controllers/OrderController.cs
using Shop.Bussiness.Service;
using Shop.Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Manager.Controllers
{
    public class OrderController : GenericApiController
    {
        // GET: Order
        public ActionResult Index()
        {
            var model = GetService<DonHangService>().GetDonHangs();
            return View(model);
        }
        public ActionResult Detail(int id)
        {
            var model = GetService<DonHangService>().GetDonHangById(id);
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var model = GetService<DonHangService>().GetDonHangById(id);
            return View(model);
        }

        public ActionResult Edit(FormCollection data)
        {
            
            var model = new DonHangModel();
            model.Id = Convert.ToInt32(data["Id"]);
            model.Date_Create = DateTime.Now;
            model.DiaChiGiaoHang = data["DiaChiGiaoHang"];
            model.Id_User = Convert.ToInt32(data["PhanTramSale"]);
            model.Complete = Convert.ToBoolean(data["Ten"]);
            model.TinhTrang = data["TinhTrang"];
            model.Id_User = Convert.ToInt32(data["Id_User"]);
            model.Note = data["Note"];
            model.Title = data["Title"];
            model.TongGia = Convert.ToDecimal(data["TongGia"]);
            model.PhiPhu = Convert.ToDecimal(data["PhiPhu"]);
            model.SanPham_Id = data["SanPham_Id"];
            GetService<DonHangService>().EditDonHang(model);
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            var model = new SanPham();
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            GetService<DonHangService>().DeleteDonHang(id);
            return RedirectToAction("Index");
        }

        public ActionResult Create(FormCollection data)
        {
            var model = new DonHangModel();
            model.Date_Create = DateTime.Now;
            model.DiaChiGiaoHang = data["DiaChiGiaoHang"];
            model.Id_User = Convert.ToInt32(data["PhanTramSale"]);
            model.Complete = Convert.ToBoolean(data["Ten"]);
            model.TinhTrang = data["TinhTrang"];
            model.Id_User = Convert.ToInt32(data["Id_User"]);
            model.Note = data["Note"];
            model.Title = data["Title"];
            model.TongGia = Convert.ToDecimal(data["TongGia"]);
            model.PhiPhu = Convert.ToDecimal(data["PhiPhu"]);
            model.SanPham_Id = data["SanPham_Id"];
            GetService<DonHangService>().AddDonHang(model);
            return RedirectToAction("Index");
        }
    }
}

Manager/Controllers/ProductController.cs
using Shop.Bussiness.Service;
using Shop.Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Manager.Controllers
{
    public class ProductController : GenericApiController
    {
        // GET: Product
        public ActionResult Index()
        {
            var model = GetService<SanPhamService>().GetSanPhams();
            return View(model);
        }
        public ActionResult Detail(int id)
        {
            var model = GetService<SanPhamService>().GetSanPhamById(id);
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var model = GetService<SanPhamService>().GetSanPhamById(id);
            return View(model);
        }

        public ActionResult Edit(FormCollection data)
        {
            var model = new SanPham();
            model.Id = Convert.ToInt32(data["Id"]);
            model.NgayNhapHang = DateTime.Parse(data["NgayNhapHang"]);
            model.PhanTramSale = Convert.ToInt32(data["PhanTramSale"]);
            model.Ten = data["Ten"];
            model.TinhTrang = data["TinhTrang"];
            model.Url_Img = data["Url_Img"];
            model.Description = data["Description"];
            model.GiaBan = Convert.ToDecimal(data["GiaBan"]);
            model.GiaNhap = Convert.ToDecimal(data["GiaNhap"]);
            GetService<SanPhamService>().EditSanPham(model);
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            var model = new SanPham();
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            GetService<SanPhamService>().DeleteSanPham(id);
            return RedirectToAction("Index");
        }

        public ActionResult Create(FormCollection data)
        {
            var model = new SanPham();
            model.NgayNhapHang = DateTime.Parse(data["NgayNhapHang"]);
            model.PhanTramSale = Convert.ToInt32(data["PhanTramSale"]);
            model.Ten = data["Ten"];
            model.TinhTrang = data["TinhTrang"];
            model.Url_Img = data["Url_Img"];
            model.Description = data["Description"];
            model.GiaBan = Convert.ToDecimal(data["GiaBan"]);
            model.GiaNhap = Convert.ToDecimal(data["GiaNhap"]);
            GetService<SanPhamService>().AddSanPham(model);
            return RedirectToAction("Index");
        }
    }
}

Manager/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Bussiness.Service;
using Shop.Common.Models;

namespace Manager.Controllers
{
    public class UserController : GenericApiController
    {
        // GET: User
        public ActionResult Index()
        {
            var model = GetService<UserService>().GetListUser();
            return View(model);
        }

        public ActionResult Create(FormCollection data)
        {
            var model = new User();
            model.DateCreate =DateTime.Now;
            model.DiaChi = data["DiaChi"];
            model.Email = data["Email"];
            model.PassWord = data["PassWord"];
            model.Phone = data["Phone"];
            model.UserName = data["UserName"];
            model.Role_Id = Convert.ToInt32(data["Role_Id"]);
            GetService<UserService>().AddUser(model);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(FormCollection data)
        {
            var model = new User();
            model.Id = Convert.ToInt32(data["Id"]);
            model.DateCreate = DateTime.Now;
            model.DiaChi = data["DiaChi"];
            model.Email = data["Email"];
            model.PassWord = data["PassWord"];
            model.Phone = data["Phone"];
            model.UserName = data["UserName"];
            model.Role_Id = Convert.ToInt32(data["Role_Id"]);
            GetService<UserService>().EditUser(model);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            GetService<UserService>().Delete(id);
            return RedirectToAction("Index");
        }

    }
}

Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quản trị</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sufee Admin - HTML5 Admin Template</title>
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">

    <link rel="stylesheet" href="~/assets/css/normalize.css">
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/assets/css/cs-skin-elastic.css">
    <!-- <link rel="stylesheet" href="assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="~/assets/scss/style.css">
    <link href="~/assets/css/lib/vector-map/jqvmap.min.css" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <style>
        body{
            margin:0px;
            padding:0px;
        }
        </style>
</head>
<body>
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">

            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
            </div>

            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="index.html"> <i class="menu-icon fa fa-server"></i>Dashboard </a>
                    </li>
                    <h3 class="menu-title">@Html.ActionLink("Trang chủ", "Index", "Home")</h3><!-- /.menu-title -->
                    <li class="menu-item-has-children "> @Html.ActionLink(" Quản lý người dùng", "Index", "User")</li>
                    <li class="menu-item-has-children "> @Html.ActionLink(" Quản lý kho hàng", "Index", "Product")</li>
                    <li class="menu-item-has-children "> @Html.ActionLink(" Quản lý đơn hàng", "Index", "Order")</li>
                    <li class="menu-item-has-children "> @Html.ActionLink(" Quản lý bình luận", "Index", "Comment")</li>
                    <li class="menu-item-has-children "> @Html.ActionLink(" Quản lý giỏ hàng", "Index", "Comment")</li>
                    <li class="menu-item-has-children "> @Html.ActionLink(" Quản lý tag", "Index", "Comment")</li>
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>Quản lý đăng nhập</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="menu-icon fa fa-sign-in"></i><a href="page-login.html">Đăng nhập</a></li>
                            <li><i class="menu-icon fa fa-sign-in"></i><a href="page-register.html">Đăng ký</a></li>
                            <li><i class="menu-icon fa fa-paper-plane"></i><a href="pages-forget.html">Quên mật khẩu</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside><!-- /#left-panel -->
    <div id="right-panel" class="right-panel">

        <!-- Header-->
        <header id="header" class="header">

            <div class="header-menu">

                <div class="col-sm-7">
                    <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                    <div class="header-left">
                        <button class="search-trigger"><i class="fa fa-search"></i></button>
                        <div class="form-inline">
                            <form class="search-form">
                                <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                                <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                            </form>
                        </div>

                        <div class="dropdown for-notification">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-bell"></i>
                                <span class="count bg-danger">5</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="notification">
                                <p class="red">You have 3 Notification</p>
                                <a class="dropdown-item media bg-flat-color-1" href="#">
                                    <i class="fa fa-check"></i>
                                    <p>Server #1 overloaded.</p>
                                </a>
                                <a class="dropdown-item media bg-flat-color-4" href="#">
                                    <i class="fa fa-info"></i>
                                    <p>Server #2 overloaded.</p>
                                </a>
                                <a class="dropdown-item media bg-flat-color-5" href="#">
                                    <i class="fa fa-warning"></i>
                                    <p>Server #3 overloaded.</p>
                                </a>
                            </div>
                        </div>

                        <div class="dropdown for-message">
                            <button class="btn btn-secondary dropdown-toggle" type="button"
                                    id="message"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="ti-email"></i>
                                <span class="count bg-primary">9</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="message">
                                <p class="red">You have 4 Mails</p>
                                <a class="dropdown-item media bg-flat-color-1" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/1.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Jonathan Smith</span>
                                        <span class="time float-right">Just now</span>
                                        <p>Hello, this is an example msg</p>
                                    </span>
                                </a>
                                <a class="dropdown-item media bg-flat-color-4" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/2.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Jack Sanders</span>
                                        <span class="time float-right">5 minutes ago</span>
                                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                                    </span>
                                </a>
                                <a class="dropdown-item media bg-flat-color-5" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/3.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Cheryl Wheeler</span>
                                        <span class="time float-right">10 minutes ago</span>
                                        <p>Hello, this is an example msg</p>
                                    </span>
                                </a>
                                <a class="dropdown-item media bg-flat-color-3" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/4.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Rachel Santos</span>
                                        <span class="time float-right">15 minutes ago</span>
                                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-5">
                    <div class="user-area dropdown float-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="user-avatar rounded-circle" src="images/admin.jpg" alt="User Avatar">
                        </a>

                        <div class="user-menu dropdown-menu">
                            <a class="nav-link" href="#"><i class="fa fa- user"></i>My Profile</a>

                            <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>

                            <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>

                            <a class="nav-link" href="#"><i class="fa fa-power -off"></i>Logout</a>
                        </div>
                    </div>

                    <div class="language-select dropdown" id="language-select">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="language" aria-haspopup="true" aria-expanded="true">
                            <i class="flag-icon flag-icon-us"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="language">
                            <div class="dropdown-item">
                                <span class="flag-icon flag-icon-fr"></span>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-es"></i>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-us"></i>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-it"></i>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </header>
        <div class="breadcrumbs">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Quản lý Người dùng</h1>
                    </div>
                </div>
            </div>
        </div>
        @RenderBody()
    </div>

    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <ul>
              <li>  @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>

                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
            </ul>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("pagespecific", required: false)
    <script src="~/assets/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="~/assets/js/plugins.js"></script>
    <script src="~/assets/js/main.js"></script>

</body>
</html>